### ISSUE TITLE
[question]: `ParseErrorCode` why `const enum`?

### ISSUE THREAD

**Issue by kittaakos** [Microsoft/node-jsonc-parser#13]
Just a question: Why did you switch from `enum` to `const enum`? I guess you had a good reason. Is there a better way to map the error code number to its "human-readable" name? Below snippet used to work before [this change](https://github.com/Microsoft/node-jsonc-parser/commit/f447db569b46267157394ba203f8c6283c338f1e#diff-8cfead41d88ad47d44509a8ab0a109adR131). Thanks!

```ts
if (parsingErrors && errors) {
    for (const error of parsingErrors) {
        errors.push(`${parser.ParseErrorCode[error.error]} at ${error.offset} offset of ${error.length} length`);
    }
}
```
[Source](https://github.com/theia-ide/theia/blob/e619393d725bbf5a05b260169193c7c538e55e4c/packages/keymaps/src/browser/keymaps-parser.ts#L59-L63)

----

Problems with `const enum`:
```ts
enum E {
    A = 0,
    B = 1
}

const enum CE {
    CA = 2,
    CB = 3
}

console.log(E[E.A]); // `A`
console.log(CE[CE.CA]); // A const enum member can only be accessed using a string literal.
```

**Comment by aeschli** [comment]
I did it to avoid cyclic dependencies between modules, which is a problem when packing with webpack.
The cyclic dependencies occurred when I tried to keep all APIs in one module while breaking up implementations.
Not saying that there's no other way of doing this.
Also having const enums has some performance benefits, but admittedly for error constants that not so much an issue (but e.g. for scanner tokens).

I could add printParseErrorCode API that turns the const to a string. What do you think?

**Comment by aeschli** [comment]
See https://github.com/Microsoft/node-jsonc-parser/commit/499e95bc1c2fc1b8923e661e219d13ab40923723

**Comment by kittaakos** [comment]
> See [499e95b](https://github.com/Microsoft/node-jsonc-parser/commit/499e95bc1c2fc1b8923e661e219d13ab40923723)

👍 Great, thank you!
