### ISSUE TITLE
Remove dependency to `vscode-nls`

### ISSUE THREAD

**Issue by jtheoof** [Microsoft/node-jsonc-parser#2]
This is a great parser.

However the fact that it relies on `vscode-nls` make it less suitable in a browser environment. `vscode-nls` pulls `fs` (node filesystem core lib) which is not available in browser. Also it's doing some dynamic `require` which is not wepback-safe:

```json
{
 "node": {
        "fs": "empty"
    }
}
```

> WARNING in ./~/vscode-nls/lib/main.js
> 118:23-44 Critical dependency: the request of a dependency is an expression

Without the `empty` config for `fs` I would get:

> WARNING in ./~/vscode-nls/lib/main.js
> 118:23-44 Critical dependency: the request of a dependency is an expression

> ERROR in ./~/vscode-nls/lib/main.js
> Module not found: Error: Can't resolve 'fs' in '/Users/jattali/dev/mnubo/front-end/node_modules/vscode-nls/lib'
> @ ./~/vscode-nls/lib/main.js 7:9-22
> @ ./~/jsonc-parser/lib/main.js

Since `vscode-nls` is only used for localizations of error, I would say it's not critical to remove it.

What do you think @aeschli ?

**Comment by aeschli** [comment]
good point. I removed the nls dependency with c8c06cc4ea0640f9318487069876f3cd35fa91f4.
Released as jsonc-parser@1.0.0

**Comment by jtheoof** [comment]
Thanks this is great!
