### ISSUE TITLE
Upgrading from 2.1.1 to 2.2.0 has diagnostic for file with only comments

### ISSUE THREAD

**Issue by dsherret** [microsoft/node-jsonc-parser#31]
The following jsonc file returns a diagnostic in 2.2.0:

```
/// test
//////asdf
```

Diagnostic:

```
ValueExpected:  (20)
```

I know this is a rare scenario, but I believe this is a valid jsonc file and a diagnostic should not be created.

Additionally, in this scenario the return value of `parser.parseTree` is undefined yet the return value is not defined as possibly returning that value.

**Comment by aeschli** [comment]
Use `ParseOption.allowEmptyContent` to allow such inputs again.

**Comment by dsherret** [comment]
@aeschli I think the changelog should be updated for 2.2—it says `allowTrailingComma` was added instead of `allowEmptyContent`. Also, this is a breaking change so it probably should have been a major version increase, but that's not a big deal as this is a pretty rare scenario.

As always, thanks for the library!

**Comment by aeschli** [comment]
You are right, should have been a major version change.
Updated the readme.
