### ISSUE TITLE
export mjs for esm

### ISSUE THREAD

**Issue by xiaoxiangmoe** [microsoft/node-jsonc-parser#36]
https://nodejs.org/api/esm.html#esm_conditional_exports

Add support for esm. Compile file into `./lib/esm/main.mjs`.

Currently ts does not support mjs, can we consider using rollup packaging?

**Comment by xiaoxiangmoe** [comment]
see  https://github.com/microsoft/node-jsonc-parser/pull/37 and https://github.com/microsoft/node-jsonc-parser/pull/38. Choose one to merge and close this issue.

**Comment by xiaoxiangmoe** [comment]
@aeschli any update?

**Comment by aeschli** [comment]
Sorry, I have no experience with the new, experimental `exports` property but I'm afraid the suggested change will break current users.

But maybe you can elaborate a bit what the advantages are. What packagers/ runtime do already support it?

**Comment by xiaoxiangmoe** [comment]
https://github.com/rollup/rollup/blob/master/package.json#L142-L151
https://github.com/xiaoxiangmoe/utils-ts/blob/master/package.json#L7-L16

**Comment by xiaoxiangmoe** [comment]
Any update on this？@aeschli

**Comment by aeschli** [comment]
Hi @xiaoxiangmoe, see my comment above. I'm still waiting for some explanation what the advantages of the change is.

We already support the `module` property. We don't have the proper esm inport syntax (no file extension), but from what I know, rollup and webpack can work with it.

**Comment by aeschli** [comment]
Closing. I need more help here to understand what the advantages are.
