### ISSUE TITLE
Interference between comment endings and glob's notations

### ISSUE THREAD

**Issue by ahuglajbclajep** [microsoft/node-jsonc-parser#41]
The following jsonc causes a parse error on VS Code 1.48.0.

```jsonc
{
  /*
  "files.exclude": {
    "**/node_modules": true
  }
  */
}
```

**Comment by aeschli** [comment]
That as designed, the comment ends with the first occurrence of `*/` and that how it is for many other languages.
The comment content is just pure text. There's no syntax like quoted strings defined for comment content.
