### ISSUE TITLE
Unescaped tabs in strings should not be supported

### ISSUE THREAD

**Issue by fabiospampinato** [microsoft/node-jsonc-parser#63]
The following throws in JS:

```ts
JSON.parse ( `"tab ->	"` );
```

But it parses with this library:

```ts
require ( 'jsonc-parser' ).parse ( `"tab ->	"` );
```

IMO that breakage from the spec is a bug, as it goes beyond what jsonc-parser says it does (namely parsing JSON with comments and trailing commas basically).

**Comment by aeschli** [comment]
The error is reported, but `parse` is fault tolerant and still returns an object.

You can see the error if you pass along the error collector:
```
let errors = []; require ( '.' ).parse ( `"tab ->     "`, errors );  console.log(errors);

[ { error: 16, offset: 0, length: 9 } ]
``

**Comment by aeschli** [comment]
In VS Code:
![image](https://user-images.githubusercontent.com/6461412/199497663-c7a620d3-544e-4e4d-a273-b8395579cd5e.png)
