### ISSUE TITLE
ncc & v3.1.0

### ISSUE THREAD

**Issue by daiyam** [microsoft/node-jsonc-parser#68]
Hello,

I'm using [ncc](https://github.com/vercel/ncc) to bundle a vscode extension which is using this library.
With `v3.0.0`, I don't have any issue.
With `v3.1.0`, `ncc` doesn't produce any errors but when running the extension, I get `Cannot find module './format'`

**Comment by aeschli** [comment]
Looks like the helper function that the TypeScript compile added to edit.js (`ar __assign = (this && this.__assign) || function () {...` confused `ncc` and it would no longer replace `require('./format')`.

The latest jsonc-parser@3.2.0 is built for `es2020` where the helper function is no longer needed.

**Comment by daiyam** [comment]
No issue with the newer version. Thx
