### ISSUE TITLE
v3.2.1 has a breaking change

### ISSUE THREAD

**Issue by ljharb** [microsoft/node-jsonc-parser#85]
Specifically, it uses the `??` operator, which doesn't work in node 12 (and breaks eslint-plugin-import tests).

It was added here: https://github.com/microsoft/node-jsonc-parser/pull/81#discussion_r1489833516

Please remove use of this operator and publish a v3.2.2?

(I'm happy to make a PR if that's needed)

**Comment by ljharb** [comment]
ping @aeschli

**Comment by aeschli** [comment]
We want to move forward and not commit to be backward compatible. We currently compile against es2020 and for that you need Node 14.
Node 12 has reached end of line status almost 2 years ago.

Is there maybe a packager that you can useto back-compile?

**Comment by aeschli** [comment]
We actually switched to es2020 already for 3.2.0. This is documented in the [CHANGELOG}( https://github.com/microsoft/node-jsonc-parser/blob/main/CHANGELOG.md)

Maybe what should have happend is to add an `engine` property. I will add that ASAP.

**Comment by ljharb** [comment]
ok, that’s still a breaking change in v3.2.0. You have to bump the major when you drop any platform/engine.
