### ISSUE TITLE
v3.3.0 induce breaking changes in some packages of the ecosystem

### ISSUE THREAD

**Issue by Zer0xxxx** [microsoft/node-jsonc-parser#91]
Hello!
I've noticed that some packages (for example: wireit) have been broken with the release of the v3.3.0 of jsonc-parser.

Related to: https://github.com/google/wireit/issues/1111

**Comment by rijkvanzanten** [comment]
I've been seeing the same behavior starting 3.3.0. In my case it's through the use of rollup-plugin-esbuild, but the symptom and results are the same.

```
file:///{{REDACTED}}/node_modules/rollup-plugin-esbuild/dist/index.mjs:11
import { parse } from "jsonc-parser";
         ^^^^^
SyntaxError: Named export 'parse' not found. The requested module 'jsonc-parser' is a CommonJS module, which may not support all module.exports as named exports.
```

**Comment by jakebailey** [comment]
See also:

- https://github.com/microsoft/node-jsonc-parser/pull/78#issuecomment-2186933283
- https://github.com/microsoft/node-jsonc-parser/pull/90#issuecomment-2186954613

**Comment by aeschli** [comment]
Fix is on the way, I'll revert the change.

**Comment by jakebailey** [comment]
3.3.1 has brought things back to the way they were before:

- https://arethetypeswrong.github.io/?p=jsonc-parser%403.3.1
- https://publint.dev/jsonc-parser@3.3.1

**Comment by Zer0xxxx** [comment]
> 3.3.1 has brought things back to the way they were before:
> 
>     * https://arethetypeswrong.github.io/?p=jsonc-parser%403.3.1
> 
>     * https://publint.dev/jsonc-parser@3.3.1

Oh my god, this is AWESOME, thank you!
Can I remove the `overrides` in my package.json (using pnpm) and check for you if all works again as expected in my project?

**Comment by jakebailey** [comment]
Yes, just avoid 3.3.0.

**Comment by Zer0xxxx** [comment]
> Yes, just avoid 3.3.0.

It works for me, using wireit, all works again as expected, thank you!

**Comment by Zer0xxxx** [comment]
Hello @jakebailey 
Should we close this issue as resolved?

**Comment by jakebailey** [comment]
Sure (I'm not on the team that works on this package so I can't do it).

**Comment by Zer0xxxx** [comment]
> Sure (I'm not on the team that works on this package so I can't do it).

Okay, let's close this this!
Feel free to reopen this issue if you need to.
